import { IHiddenFileBase } from '../HiddenFileBase'
import { CryptoMessage, DecryptResult, RSAPrivateKey, RSAPublicKey } from '../types'

export interface IHiddenFileBuyer extends IHiddenFileBase {

  /**
   * Generates and saves RSA key pair
   */
  initBuy: () => Promise<RSAPublicKey>

  /**
   * Decrypts AES key for file with saved RSA key pair.
   * @returns {@link DecryptResult} DecryptResult.ok is true if file was successfully decrypted with provided key,
   * false otherwise. DecryptResult.result will contain decrypted AES key.
   * @param encryptedAESKey AESKey used to encrypt the file,
   * but key itself is encrypted with RSAPublicKey generated by {@link initBuy}
   */
  saveFileAESKey: (encryptedAESKey: CryptoMessage) => Promise<DecryptResult>

  /**
   * Used to report fraud if {@link saveFileAESKey} failed.
   */
  revealFraudReportRSAPrivateKey: () => Promise<RSAPrivateKey>
}
